### ISSUE TITLE
can´t turn off geo functionality

### ISSUE THREAD

**Issue by dengra** [Tazaf/ionicitude#16]
Hi @Tazaf ,

First of all thanks for the great work :-)

I´m creating an app which only needs image recognition and I set my reqFeatures to 2d_tracking only:
```
      Ionicitude.init({
        reqFeatures: ['2d_tracking']
      })
        .then(function () {
          console.log('Here you go. Ionicitude is fully initialized !');
        })
        .catch(function (error) {
          console.log("Hu-ho..! Something has failed !", error);
        });
```
Everything else seems to work fine, but the app keeps asking me for GPS access and I need to avoid this since I don´t need the location and GPS consumes so much battery.

Could you help me out?
Thank you and all the best,

**Comment by Tazaf** [comment]
Hi @dengra 

Can you try `'image_tracking'`, instead of `'2d_tracking'`:

```javascript
Ionicitude.init({
  reqFeatures: ['image_tracking']
})
```
With this, my test app only asks for camera access.

Looking in the Wikitude code, it would seem that they have changed their string constants.

Tell me if that worked, so that I can update Ionicitude's documentation ;)

Note : you're using the latest Wikitude version, right ?

**Comment by dengra** [comment]
Hi @Tazaf,

yes that works, thank you very much! :-)

Yep, I´m using Wikitude´s last version, 6.1.0-3.4.2

**Comment by Tazaf** [comment]
Hey, glad it worked out 😉 !

I'll update the documentation, then.
