### ISSUE TITLE
Ionicitude.close() showing error

### ISSUE THREAD

**Issue by HardikDG** [Tazaf/ionicitude#17]
When I am trying to call 'Ionicitude.close();' in the ionic app js, it is showing me the error in the console and does not close the ARView. 

Error: 
Error in Success callbackId: WikitudePlugin1613219586 : TypeError: undefined is not an object (evaluating 'argument.handleEvent')
TypeError: undefined is not an object (evaluating 'argument.handleEvent')

Reason: 
When I debug the code the close method(WikitudePlugin.prototype.close) in the plugin file(WikitudePlugin) it is not able to find the methods for 
```
    document.removeEventListener("pause", this.onPause, false);
    document.removeEventListener("resume", this.onResume, false);
    document.removeEventListener("backbutton", this.onBackButton, false);
```

When I comment this 3 lines, the code is working and it is closing the view. 

-> When I tried with 'app.wikitudePlugin.close();' cordova plugin directly, It is working without any change and all 3 methods are found also in the close method.

**Comment by Tazaf** [comment]
Hi @HardikDG,

Could you show me exactly where you are calling `Ionicitude.close()` ?

**Comment by HardikDG** [comment]
@Tazaf 
I have tried 2 ways 
When I get current marker selection event
```
        function markerselected(service, params) {
            // alert("Selected")
            console.log('This is the marker #' + params.id + ', that is named ' + params.title + ', and that has this description: ' + params.description);
            Ionicitude.close();
            // app.wikitudePlugin.close();
        }
```

Other is independent
```
function closeAR() {
  Ionicitude.close();
}
```

I have added 2 actions like this

```
Ionicitude.addAction(markerselected);
Ionicitude.addAction(closeAR);
```

I have written this in the app.js of the main Ionic project

**Comment by Tazaf** [comment]
If all the code you showed me is in the your main `app.js` file on the Ionic side, then can you please try with this : 

```javascript
function markerselected(service, params) {
  // alert("Selected")
  console.log('This is the marker #' + params.id + ', that is named ' + params.title + ', and that has this description: ' + params.description);
  service.close(); // instead of Ionicitude.close()
}
```
With the same idea, your independant `closeAR` function should accept at least one argument, that is the Ionicitude `service`, as you did in your `markerSelected` function. So you should declare it like that :

```javascript
function closeAR(service) {
  service.close();
}
```
I remember someone having the same problem as you, that was resolved by using `service` instead of `Ionicitude` in the Action function. But I can't seem to find any reference to that discussion 🤔

Side question... In your `markerSelected` function, does your `console.log()` displaying correctly ?

By the way, you can chain your calls to `addAction()`, like so :

```javascript
Ionicitude
  .addAction(markerSelected)
  .addAction(closeAR);
```

Hope that helps !

**Comment by HardikDG** [comment]
`service.close();` is working.
Thanks for the solution and optimization tip.
