### ISSUE TITLE
Ar World launching but detection is not working

### ISSUE THREAD

**Issue by Giusti** [Tazaf/ionicitude#8]
I successfully embedded Ionictude with the newest Version of Wikitudes Plugin into my App
I am able too launch all the Worlds from the Demo, but somehow the Image detection is not working the camera is just open and nothing happens when I see the picture from the sample PDF

**Comment by Tazaf** [comment]
Hello.
If you successfully launched the AR World, that means the problem is related to Wikitude itself. The code that's handling the image detection is from them, not me.
That's a problem you should report on the Wikitude Forum or check with the Wikitude Staff.

**Comment by Giusti** [comment]
Yes I am already In contact with Wikitude, but they are talking about Ionic and Ionictude beeing the problem. I just dont get any Info after starting the Ar World I am really not sure what I am missing out I simply copied the sample worlds and assets so this cant be the problem either.... and I took the logic from your demo application when scanning the Surfer nothing happens. Maybe the new Sdk is not working properly with Ionictude? I am not getting any errors...

**Comment by Tazaf** [comment]
As I said, Ionicitude is just responsible for launching the AR World.
And the code from the worlds is directly taken from the Wikitude demo application (I didn't actually wrote it) and has nothing to do with Ionicitude (except in certain worlds like the one that takes screenshot where there is a dialog between Ionicitude and Wikitude).

It may be possible that Ionic is somewhat involved in the problem, but honestly, I wouldn't see how. Once a world is loaded, there is no more interaction between Wikitude and Ionicitude : each AR World launch creates a new Activity in the app that is completely agnostic of Ionic (and Ionicitude) and the only interaction possible is through `document.location` statements or `Ionicitude.callJavaScript()` calls, both of which are not present in the exemples where you need to scan the images.

If you'd want to be sure if the problem comes from Wikitude or Ionic + Wikitude, you could download, bundle and install the [demo application that Wikitude provide](https://github.com/Wikitude/wikitude-cordova-plugin-samples), which run only through Cordova. If you encouter the same problem in the demo app, then it comes from Wikitude itself. If not... well... we'll see ^^

**Comment by Giusti** [comment]
sadly I was not able to create the sample project from the commandline when I try it always says Command sh could not be found.... on windows

**Comment by Tazaf** [comment]
Ok.
I bundled the Wikitude Demo App into an easier to install form here : https://github.com/Tazaf/WikitudeCordovaDemoApp/tree/master

You can install it and see if the problem occurs again.

**Comment by Giusti** [comment]
I found the Problem, since I am working with Telerik the Project Structure is a little bit differen and all my folders are built into the generated www folder so when I created a www folder the plugin could not find the Worlds simply doin nothing it seems this is working on Android, But as of today I must have cracked something because now I am getting this Error both Android and iOS...

UnsupportedFeatureError
message
:
"AR World loading error : Your device does not support one or several of it's requested features."
name
:
"UnsupportedFeatureError"
stack
:
"UnsupportedFeatureError↵    at UnsupportedFeatureError.Error (native)↵    at new UnsupportedFeatureError (file:///data/user/0/com.bmtricon.Pixel/files/12590FAA-5EDD-4B12-856D-F52A0A1599F2/lib/ionicitude.min.js:1:61)↵    at Object.c [as launchAR](file:///data/user/0/com.bmtricon.Pixel/files/12590FAA-5EDD-4B12-856D-F52A0A1599F2/lib/ionicitude.min.js:1:3370)↵    at Scope.$scope.launchAR (file:///data/user/0/com.bmtricon.Pixel/files/12590FAA-5EDD-4B12-856D-F52A0A1599F2/js/controller.js:246:24)↵    at fn (eval at compile (file:///data/user/0/com.bmtricon.Pixel/files/12590FAA-5EDD-4B12-856D-F52A0A1599F2/lib/ionic/js/ionic.bundle.js:21972:15), <anonymous>:4:274)↵    at file:///data/user/0/com.bmtricon.Pixel/files/12590FAA-5EDD-4B12-856D-F52A0A1599F2/lib/ionic/js/ionic.bundle.js:57514:9↵    at Scope.$eval (file:///data/user/0/com.bmtricon.Pixel/files/12590FAA-5EDD-4B12-856D-F52A0A1599F2/lib/ionic/js/ionic.bundle.js:24673:28)↵    at Scope.$apply (file:///data/user/0/com.bmtricon.Pixel/files/12590FAA-5EDD-4B12-856D-F52A0A1599F2/lib/ionic/js/ionic.bundle.js:24772:23)↵    at HTMLAnchorElement.<anonymous> (file:///data/user/0/com.bmtricon.Pixel/files/12590FAA-5EDD-4B12-856D-F52A0A1599F2/lib/ionic/js/ionic.bundle.js:57513:13)↵    at HTMLAnchorElement.eventHandler (file:///data/user/0/com.bmtricon.Pixel/files/12590FAA-5EDD-4B12-856D-F52A0A1599F2/lib/ionic/js/ionic.bundle.js:12098:21)"

But It already worked on this device I am not really sure what the problem is at the moment..

Edit: This is weird I just made a new Build without changing anything and now it is working on Android atleast...

Regards Christopher
